#ifndef PROTOCOLO_H_INCLUDED
#define PROTOCOLO_H_INCLUDED

#define TAM_IDENTIFICADOR 16
#define TAM_NOMBRE_ARCH (TAM_IDENTIFICADOR + 4)
#define MAX_CAMPOS_POR_TABLA 8
#define TAM_MAX_TIPO_CHAR 64

typedef enum {
    BD_TODO_OK,
    BD_DATOS_OBTENIDOS,
    BD_ERROR_SIN_RESULTADOS,
    BD_ERROR_SINTAXIS,
    BD_ERROR_COMANDO,
    BD_ERROR_TABLA_EXISTE,
    BD_ERROR_TABLA_NO_EXISTE,
    BD_ERROR_DEMASIADOS_CAMPOS,
    BD_ERROR_SIN_PK,
    BD_ERROR_ACTUALIZAR_PK,
    BD_ERROR_DEMASIADOS_PK,
    BD_ERROR_DEMASIADOS_AI,
    BD_ERROR_ESCRITURA,
    BD_ERROR_LECTURA,
    BD_ERROR_CANT_CAMPOS,
    BD_ERROR_CAMPO_INEXISTENTE,
    BD_ERROR_CAMPO_INVALIDO,
    BD_ERROR_SIN_MEMO,
    BD_ERROR_ARCHIVO,
    BD_ERROR_PARAMETRO,
    BD_ERROR_TAM_TEXTO,
    BD_ERROR_CAMPO_ES_AI,
    BD_ERROR_AI_NO_ES_ENTERO,
    BD_ERROR_AI_NO_ES_PK,
    BD_ERROR_ENCABEZADO,
} eBDRetorno;

#endif // PROTOCOLO_H_INCLUDED
